# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

include: ../analysis_options.yaml
analyzer:
  exclude:
    - 'test/testdata/**.dart'
    # TODO(https://github.com/dart-lang/sdk/issues/31344): remove these.
    - 'testdata/directives_test/after.dart'
    - 'testdata/directives_test/before.dart'
    - 'testdata/double_quotes_test/after.dart'
    - 'testdata/double_quotes_test/before.dart'
