[package]
name = "xi-core"
version = "0.0.0"
license = "BSD-3-Clause"
authors = ["Raph Levien <raph@google.com>"]
description = "Main binary for xi-core in Fuchsia, using fidl for communication"
repository = "https://fuchsia.googlesource.com/xi"

[dependencies]
xi-core-lib = "0.1.0"
xi-rpc = "0.1.0"

[target.'cfg(target_os = "fuchsia")'.dependencies]
magenta = { path = "../../../../rust/magenta-rs" }
mxruntime = { path = "../../../../rust/mxruntime" }
fidl = { path = "../../../../lib/fidl/rust/fidl" }
apps_xi_services = { path = "../../../../out/debug-x86-64/gen/apps/xi/services/services" }
application_services_service_provider = { path = "../../../../out/debug-x86-64/gen/application/services/service_provider" }
