name: GeneratedApp
description: A generated Flutter project.

dependencies:
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - lib/images/def.png
  - lib/images/menu.png
  - lib/images/gallery.png