# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

flutter:
  assets:
    - packages/userpicker_device_shell/res/bg.jpg
    - packages/userpicker_device_shell/res/ArmadilloSilhouette.png
    - packages/userpicker_device_shell/res/BlackHole.png
    - packages/userpicker_device_shell/res/CapybaraSilhouette.png
    - packages/userpicker_device_shell/res/Fuchsia_Logo_40dp_Accent.png
    - packages/userpicker_device_shell/res/fuchsia.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_0_bar_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_1_bar_lock_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_1_bar_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_2_bar_lock_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_2_bar_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_3_bar_lock_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_3_bar_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_4_bar_lock_white_48dp.png
    - packages/userpicker_device_shell/res/ic_signal_wifi_4_bar_white_48dp.png
    - packages/userpicker_device_shell/res/screen_config.json
