# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: armadillo
dependencies:
  email_story:
    path: ../../modules/email/modules/story
  flutter:
    sdk: flutter
  keyboard:
    path: ../keyboard
  models:
    path: ../../modules/common/packages/models
  sysui_widgets:
    path: ../widgets
  util:
    path: ../../modules/common/packages/util
  widgets:
    path: ../../modules/common/packages/widgets
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - packages/armadillo/res/Armadillo.png
    - packages/armadillo/res/Background.jpg
    - packages/armadillo/res/flutter-mark-square-100.png
    - packages/armadillo/res/ic_airplanemode_active_black.png
    - packages/armadillo/res/ic_airplanemode_inactive_grey600.png
    - packages/armadillo/res/ic_battery_90_grey600_1x_web_24dp.png
    - packages/armadillo/res/ic_battery_90_white_1x_web_24dp.png
    - packages/armadillo/res/ic_brightness_high_grey600.png
    - packages/armadillo/res/ic_do_not_disturb_off_grey600.png
    - packages/armadillo/res/ic_do_not_disturb_on_black.png
    - packages/armadillo/res/ic_mic_grey600_1x_web_24dp.png
    - packages/armadillo/res/ic_screen_lock_rotation_black.png
    - packages/armadillo/res/ic_screen_rotation_black.png
    - packages/armadillo/res/ic_signal_cellular_connected_no_internet_0_bar_grey600_24dp.png
    - packages/armadillo/res/ic_signal_wifi_3_bar_grey600_24dp.png
    - packages/armadillo/res/ic_volume_up_grey600.png
    - packages/armadillo/res/initial_story_generator_config.json
    - packages/armadillo/res/logo_googleg_24dpx4.png
    - packages/armadillo/res/placeholder_grid.png
    - packages/armadillo/res/screen_config.json
    - packages/armadillo/res/stories.json
    - packages/armadillo/res/User.png
    - packages/keyboard/res/ArrowDown.png
    - packages/keyboard/res/ArrowUp.png
    - packages/keyboard/res/Delete.png
    - packages/keyboard/res/Space.png
  fonts:
    - family: Roboto
      fonts:
        - asset: ../../fonts/third_party/roboto/Roboto-Regular.ttf
        - asset: ../../fonts/third_party/roboto/Roboto-Italic.ttf
          style: italic
        - asset: ../../fonts/third_party/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: ../../fonts/third_party/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: ../../fonts/third_party/roboto/Roboto-Light.ttf
          weight: 300
        - asset: ../../fonts/third_party/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ../../fonts/third_party/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: ../../fonts/third_party/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../../fonts/third_party/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: ../../fonts/third_party/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ../../fonts/third_party/roboto/Roboto-Black.ttf
          weight: 900
        - asset: ../../fonts/third_party/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: RobotoCondensed
      fonts:
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-Regular.ttf
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-Italic.ttf
          style: italic
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: ../../fonts/third_party/robotocondensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
