[package]
name = "spinning_square_rs"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Rob Tsuk <robtsuk@google.com>"]
description = "Example of a Fuchsia module in Rust"
repository = "https://fuchsia.googlesource.com/rust_sample_module"

[dependencies.cairo-rs]
version = "0.1.3"
default-features = false
features = ["png"]
