name: gallery
description: View UI Widgets and screens.
dependencies:
  flutter:
    sdk: flutter
  auth:
    path: ../packages/auth
  clients:
    path: ../packages/clients
  models:
    path: ../packages/models
  services:
    path: ../packages/services
  widgets:
    path: ../packages/widgets
