name: gallery
description: View UI Widgets and screens.
dependencies:
  flutter:
    path: ../third_party/flutter/packages/flutter
  models:
    path: ../packages/models
  widgets:
    path: ../packages/widgets
