# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: perspective
flutter:
  uses-material-design: true
  assets:
    - packages/perspective/res/module-a-photos/1-sea-withtext.png
    - packages/perspective/res/module-a-photos/2-pano-withtext.png
    - packages/perspective/res/module-b-gallery-photos/1.png
    - packages/perspective/res/module-b-gallery-photos/2.png
    - packages/perspective/res/module-b-gallery-photos/3.png
    - packages/perspective/res/module-b-gallery-photos/4.png
    - packages/perspective/res/module-b-gallery-photos/5.png
    - packages/perspective/res/module-b-gallery-photos/6.png
    - packages/perspective/res/module-b-gallery-photos/7.png
    - packages/perspective/res/module-b-gallery-photos/8.png
    - packages/perspective/res/module-b-gallery-photos/9.png
    - packages/perspective/res/module-b-gallery-photos/10.png
    - packages/perspective/res/module-b-gallery-photos/11.png
    - packages/perspective/res/module-c-video/1-vid.png
