# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: sysui_widgets
dependencies:
  flutter:
    path: ../third_party/flutter/packages/flutter
dev_dependencies:
  # Note that this dependency also gets us the test package.
  # Not specifying test explicitly here to ensure we use the same version as
  # Flutter.
  flutter_test:
    path: ../third_party/flutter/packages/flutter_test
  typed_mock: ^0.0.4
