# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: blackjack

flutter:
  assets:
    - images/avatars/aparna.png
    - images/avatars/danielle.png
    - images/avatars/empty-seat.png
    - images/avatars/simon.png

    - images/cards/back.png
    - images/cards/10-clubs.png
    - images/cards/2-clubs.png
    - images/cards/3-clubs.png
    - images/cards/4-clubs.png
    - images/cards/5-clubs.png
    - images/cards/6-clubs.png
    - images/cards/7-clubs.png
    - images/cards/8-clubs.png
    - images/cards/9-clubs.png
    - images/cards/a-clubs.png
    - images/cards/j-clubs.png
    - images/cards/k-clubs.png
    - images/cards/q-clubs.png
    - images/cards/10-diamonds.png
    - images/cards/2-diamonds.png
    - images/cards/3-diamonds.png
    - images/cards/4-diamonds.png
    - images/cards/5-diamonds.png
    - images/cards/6-diamonds.png
    - images/cards/7-diamonds.png
    - images/cards/8-diamonds.png
    - images/cards/9-diamonds.png
    - images/cards/a-diamonds.png
    - images/cards/j-diamonds.png
    - images/cards/k-diamonds.png
    - images/cards/q-diamonds.png
    - images/cards/10-hearts.png
    - images/cards/2-hearts.png
    - images/cards/3-hearts.png
    - images/cards/4-hearts.png
    - images/cards/5-hearts.png
    - images/cards/6-hearts.png
    - images/cards/7-hearts.png
    - images/cards/8-hearts.png
    - images/cards/9-hearts.png
    - images/cards/a-hearts.png
    - images/cards/j-hearts.png
    - images/cards/k-hearts.png
    - images/cards/q-hearts.png
    - images/cards/10-spades.png
    - images/cards/2-spades.png
    - images/cards/3-spades.png
    - images/cards/4-spades.png
    - images/cards/5-spades.png
    - images/cards/6-spades.png
    - images/cards/7-spades.png
    - images/cards/8-spades.png
    - images/cards/9-spades.png
    - images/cards/a-spades.png
    - images/cards/j-spades.png
    - images/cards/k-spades.png
    - images/cards/q-spades.png

    - images/chips/decrease_bet.png
    - images/chips/half.png
    - images/chips/increase_bet.png
    - images/chips/whole.png

    - images/results/blackjack.png
    - images/results/bust.png
    - images/results/draw.png
    - images/results/lose.png
    - images/results/win.png

    - images/table/1-highlighted.png
    - images/table/2-highlighted.png
    - images/table/3-highlighted.png
    - images/table/4-highlighted.png
    - images/table/5-highlighted.png
    - images/table/6-highlighted.png
    - images/table/dealer-highlighted.png
    - images/table/no-highlights.png
